projectName:
  type: input
  prompt: "What is the project name?"
  default: "Demo da daily de titulo pro README"
  option: "projectName"

description:
  type: input
  prompt: "Enter a project description"
  default: "Esse é um projeto demo da daily de titulo pro README e outros patches"
  option: "description"

version:
  type: input
  prompt: "Project version"
  default: "1.0"
  option: "version"

deleteBase24:
  type: choose
  prompt: "Delete Base24 configuration?"
  default: "Não"
  choices:
    - Sim
    - Não
  option: "options.deleteBase24"