name:
    type: input
    prompt: "What is the project name?"
    default: "Batch Template"
    option: "name"

description:
    type: input
    prompt: "Enter a project description"
    default: "template em python para processamento batch."
    option: "description"

version:
    type: input
    prompt: "Project version"
    default: "1.0"
    option: "version"
