name:
    type: input
    prompt: "What is the project name?"
    default: "Buora Template"
    option: "name"

description:
    type: input
    prompt: "Enter a project description"
    default: "Demo do template do buora para criar um projeto com a estrutura de pastas e arquivos padrão."
    option: "description"

version:
    type: input
    prompt: "Project version"
    default: "1.0"
    option: "version"
