project:
  type: string
  prompt: "Qual é o nome do projeto?"
  default: "Infra buora"
  option: "name"


description:
  type: string
  prompt: "Qual é a descrição do projeto?"
  default: "infraestrutura para o projeto buora"
  option: "description"

agent1:
  type: list
  prompt: "Você quer incluir a pasta agent1?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeAgent1"

fn_authorizers:
  type: list
  prompt: "Você quer incluir a pasta fn_authorizers?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeFnAuthorizers"

fn_conversation_db:
  type: list
  prompt: "Você quer incluir a pasta fn_conversation_db?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeFnConversationDb"

frontend:
  type: list
  prompt: "Você quer incluir a pasta frontend?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeFrontend"

docs:
  type: list
  prompt: "Você quer incluir a pasta docs?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeDocs"

terrafrom:
  type: list
  prompt: "Você quer incluir a pasta terrafrom?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeTerraform"