name:
  type: input
  prompt: "What is the project name?"
  default: "Buora Template"
  option: "name"

description:
  type: input
  prompt: "Enter a project description"
  default: "Demo do template do buora para criar um projeto com a estrutura de pastas e arquivos padrão."
  option: "description"

version:
  type: input
  prompt: "Project version"
  default: "1.0"
  option: "version"

includeDocs:
  type: choose
  prompt: "Include documentation folder?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeDocs"

includeFrontend:
  type: choose
  prompt: "Include frontend structure?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeFrontend"

includeTerraform:
  type: choose
  prompt: "Include Terraform configuration?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeTerraform"

includeAgent1:
  type: choose
  prompt: "Include Agent1 module?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeAgent1"

includeFnAuthorizers:
  type: choose
  prompt: "Include Function Authorizers?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeFnAuthorizers"

includeFnConversationDb:
  type: choose
  prompt: "Include Conversation Database Function?"
  default: "Sim"
  choices:
    - Sim
    - Não
  option: "options.includeFnConversationDb"